---
- name: Create systemd service file for Minecraft
  ansible.builtin.template:
    src: minecraft.service.j2
    dest: /etc/systemd/system/minecraft.service
    owner: root
    group: root
    mode: "0644"
  notify: Reload systemd and start Minecraft
