---
- name: Stop minecraft service before configuring plugins
  ansible.builtin.service:
    name: minecraft
    state: stopped

# Configuere ALL the plugins here

- name: Start minecraft service after configuring plugins
  ansible.builtin.service:
    name: minecraft
    state: restarted

- name: Wait for server to come up after plugin config
  ansible.builtin.wait_for:
    port: "{{ server_port }}"
    state: started
    timeout: "{{ startup_timeout }}"
  register: plugin_config_restart

- name: Check startup result after plugin config
  ansible.builtin.fail:
    msg: "The Minecraft service did not start within {{ startup_timeout }} seconds"
  when: not plugin_config_restart.elapsed
