---
- name: Install EPEL
  ansible.builtin.package:
    name:
      - epel-release
    state: present

- name: Install packages
  ansible.builtin.package:
    name:
      - vim
      - lynx
      - unzip
    state: present

- name: ED25519 keypair for root
  community.crypto.openssh_keypair:
    comment: root@fsitma1.fsitma.com
    force: false
    path: "{{ linux_keyfile }}"
    type: "ed25519"

- name: Make public key public-readable
  ansible.builtin.file:
    group: root
    mode: "0644"
    owner: root
    path: "{{ linux_keyfile }}.pub"

- name: Check if firewalld service unit file exists
  ansible.builtin.stat:
    path: /etc/systemd/system/multi-user.target.wants/firewalld.service
  register: linux_firewalld_unit_file

- name: Disable and stop firewalld if installed
  ansible.builtin.service:
    name: firewalld
    state: stopped
    enabled: false
  when: linux_firewalld_unit_file.stat.exists
