---
- name: Install/configure fail2ban
  hosts: servers
  become: false

  vars:
    local: /etc/fail2ban/jail.local

  tasks:
    - name: Install fail2ban
      ansible.builtin.package:
        name:
          - fail2ban-all
        state: present
      notify: Restart_fail2ban

    - name: Enable fail2ban
      ansible.builtin.service:
        name: fail2ban
        enabled: true
      notify: Restart_fail2ban

    - name: Copy base configuration
      ansible.builtin.copy:
        force: false
        src: /etc/fail2ban/jail.conf
        remote_src: true
        dest: "{{ local }}"
        mode: "0644"
        owner: root
        group: root
      notify: Restart_fail2ban

    - name: Enable jails
      community.general.ini_file:
        path: "{{ local }}"
        section: "{{ item }}"
        option: enabled
        value: true
        mode: "0644"
        backup: false
      with_items:
        - sshd
      notify: Restart_fail2ban

  handlers:
    - name: Restart_fail2ban
      ansible.builtin.service:
        name: fail2ban
        state: restarted
