---
- name: Deploy Minecraft Server with PaperMC
  hosts: servers

  vars:
    minecraft_version: "1.21.5"
    paper_version: "{{ minecraft_version }}"
    paper_build_number: "114"
      #    minecraft_server_dir: "/opt/minecraft/lotuscove"
      #    minecraft_user: "minecraft"
      #    minecraft_group: "{{ minecraft_user }}"

    paper_base: "https://fill-data.papermc.io/v1/objects"
    paper_jar_name: "paper-{{ paper_version }}-{{ paper_build_number }}.jar"
    paper_jar_checksum: "2ae6ae22adf417699746e0f89fc2ef6cb6ee050a5f6608cee58f0535d60b509e"
    paper_jar_url: "{{ paper_base }}/{{ paper_jar_checksum }}/{{ paper_jar_name }}"

    propfile: "server.properties"
    local_server_properties_path: "/home/paulbort/work/LotusCoveSample/{{ propfile }}"

  tasks:
    - name: Create minecraft group
      ansible.builtin.group:
        name: "{{ minecraft_group }}"
        state: present

    - name: Create minecraft user
      ansible.builtin.user:
        name: "{{ minecraft_user }}"
        group: "{{ minecraft_group }}"
        system: true
        create_home: true
        home: "{{ minecraft_server_dir }}"
        shell: "/bin/nologin"
        state: present

    - name: Create Minecraft server directory
      ansible.builtin.file:
        path: "{{ minecraft_server_dir }}"
        state: directory
        owner: "{{ minecraft_user }}"
        group: "{{ minecraft_group }}"
        mode: "0755"
        recurse: true

    - name: Download PaperMC server JAR
      ansible.builtin.get_url:
        url: "{{ paper_jar_url }}"
        dest: "{{ minecraft_server_dir }}/{{ paper_jar_name }}"
        owner: "{{ minecraft_user }}"
        group: "{{ minecraft_group }}"
        mode: "0644"
        checksum: "sha256:{{ paper_jar_checksum }}"
        validate_certs: true

    - name: Link generic server.jar to PaperMC JAR
      # (So we don't have to update the systemd unit file)
      ansible.builtin.file:
        src: "{{ minecraft_server_dir }}/{{ paper_jar_name }}"
        dest: "{{ minecraft_server_dir }}/server.jar"
        state: link
        owner: "{{ minecraft_user }}"
        group: "{{ minecraft_group }}"

    - name: Copy existing server.properties
      ansible.builtin.copy:
        src: "{{ local_server_properties_path }}"
        dest: "{{ minecraft_server_dir }}/server.properties"
        owner: "{{ minecraft_user }}"
        group: "{{ minecraft_group }}"
        mode: "0644"

    - name: Create EULA file (PaperMC also requires EULA)
      ansible.builtin.copy:
        content: |
          #By changing the setting below to TRUE you are indicating your agreement to our EULA (https://aka.ms/MinecraftEULA).
          #Fri Jul 25 17:30:00 EDT 2025 # Adjust date as desired
          eula=true
        dest: "{{ minecraft_server_dir }}/eula.txt"
        owner: "{{ minecraft_user }}"
        group: "{{ minecraft_group }}"
        mode: "0644"

    - name: Create systemd service file for Minecraft
      ansible.builtin.template:
        src: minecraft.service.j2 # Create this template file
        dest: /etc/systemd/system/minecraft.service
        owner: root
        group: root
        mode: "0644"
      notify: Reload systemd and start Minecraft

  handlers:
    - name: Reload systemd and start Minecraft
      ansible.builtin.systemd:
        daemon_reload: true
        name: minecraft
        state: started
        enabled: true
