---
- name: Install web server
  ansible.builtin.package:
    name:
      - httpd
      - mod_ssl
      - mod_md
      - certbot
      - certbot-apache
    state: present

- name: Set ServerName
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: "^ServerName"
    line: "ServerName {{ dns_name }}"
    state: present

- name: Start / enable httpd
  ansible.builtin.service:
    name: httpd
    state: restarted
    enabled: true
