---
- name: Stop minecraft service before installing plugin
  ansible.builtin.service:
    name: minecraft
    state: stopped

- name: Download plugin
  # Why are we downloading after stopping?
  # Because we are downloading directly to the plugins/ directory.
  ansible.builtin.get_url:
    url: "https://github.com/mesacarlos/WebConsole/releases/download/v2.8/WebConsole-2.8.jar"
    dest: "{{ plugins_dir }}/{{ console_name }}.jar"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: "0644"

- name: Start minecraft service after installing plugin
  ansible.builtin.service:
    name: minecraft
    state: restarted

- name: Wait for server to come up after plugin install
  ansible.builtin.wait_for:
    port: "{{ server_port }}"
    state: started
    timeout: "{{ startup_timeout }}"
  register: console_restart_1

- name: Check startup result after plugin install
  ansible.builtin.fail:
    msg: "The Minecraft service did not start within {{ startup_timeout }} seconds"
  when: not console_restart_1.elapsed

- name: Check for WebConsole open port
  ansible.builtin.wait_for:
    port: "{{ console_port }}"
    state: started
    timeout: "{{ startup_timeout }}"
  register: console_port_status

- name: Check startup result after plugin config
  ansible.builtin.fail:
    msg: "The WebConsole plugin is not listening on port {{ console_port }}"
  when: not console_port_status.elapsed
