---
- name: Install WebConsole plugin
  ansible.builtin.include_role:
    name: pluginst
  vars:
    pluginst_name: "WebConsole"
    pluginst_url: "https://github.com/mesacarlos/WebConsole/releases/download/v2.8/WebConsole-2.8.jar"

- name: Check for WebConsole open port
  ansible.builtin.wait_for:
    port: "{{ console_port }}"
    timeout: "{{ startup_timeout }}"
